import { useState } from 'react';
import { Target, Users, Compass, AlertTriangle, Copy, Check, Download, FileText, Info, TrendingUp, Code, ListChecks, FileCode } from 'lucide-react';
import type { ClarificationResult } from '../utils/clarifyProblem';

interface ClarificationOutputProps {
  data: ClarificationResult;
  onGeneratePRD?: () => void;
}

export function ClarificationOutput({ data, onGeneratePRD }: ClarificationOutputProps) {
  const [copied, setCopied] = useState(false);
  const [showPRDPrompt, setShowPRDPrompt] = useState(true);

  const copyAllToClipboard = async () => {
    const content = `PROBLEM → SOLUTION CLARIFICATION

📋 REFINED PROBLEM STATEMENT
${data.problemStatement}

👥 TARGET USERS
${data.targetUsers}

💔 USER PAIN POINTS
${data.userPainPoints.map((point, i) => `• ${point}`).join('\n')}

🧭 PROPOSED SOLUTION DIRECTION
${data.solutionDirection}

✨ KEY FEATURES
${data.keyFeatures.map((feature, i) => `✓ ${feature}`).join('\n')}

⚠️ ASSUMPTIONS & RISKS
${data.assumptionsRisks}

📊 SUCCESS METRICS
${data.successMetrics.map((metric, i) => `${i + 1}. ${metric}`).join('\n')}

💻 TECHNICAL CONSIDERATIONS
${data.technicalConsiderations}

✅ RECOMMENDED NEXT STEPS
${data.nextSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}`;

    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const exportAsText = () => {
    const content = `
PROBLEM → SOLUTION CLARIFICATION
Generated: ${new Date().toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📋 REFINED PROBLEM STATEMENT
${data.problemStatement}


👥 TARGET USERS
${data.targetUsers}

💔 USER PAIN POINTS
${data.userPainPoints.map((point, i) => `${i + 1}. ${point}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🧭 PROPOSED SOLUTION DIRECTION
${data.solutionDirection}

✨ KEY FEATURES
${data.keyFeatures.map((feature, i) => `${i + 1}. ${feature}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚠️ ASSUMPTIONS & RISKS
${data.assumptionsRisks}

📊 SUCCESS METRICS
${data.successMetrics.map((metric, i) => `${i + 1}. ${metric}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💻 TECHNICAL CONSIDERATIONS
${data.technicalConsiderations}

✅ NEXT STEPS
${data.nextSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `problem-clarification-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportAsMarkdown = () => {
    const content = `# Problem → Solution Clarification

**Generated:** ${new Date().toLocaleString()}

---

## 📋 Refined Problem Statement

${data.problemStatement}


---

## 👥 Target Users

${data.targetUsers}

### 💔 User Pain Points

${data.userPainPoints.map((point, i) => `${i + 1}. ${point}`).join('\n')}

---

## 🧭 Proposed Solution Direction

${data.solutionDirection}

### ✨ Key Features

${data.keyFeatures.map((feature, i) => `${i + 1}. ${feature}`).join('\n')}

---

## ⚠️ Assumptions & Risks

${data.assumptionsRisks}

### 📊 Success Metrics

${data.successMetrics.map((metric, i) => `${i + 1}. ${metric}`).join('\n')}

---

## 💻 Technical Considerations

${data.technicalConsiderations}

### ✅ Next Steps

${data.nextSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

---

*Generated by Problem → Solution Clarifier*
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `problem-clarification-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Main Clarification Content */}
      <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-lg p-8 space-y-8">
        {/* Header with Copy All Button */}
        <div className="border-b border-slate-200 dark:border-slate-700 pb-4">
          <div className="flex items-center justify-between gap-4">
            <div>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white">Clarified Breakdown</h2>
              <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
                Comprehensive analysis of your problem statement
              </p>
            </div>
            <button
              onClick={copyAllToClipboard}
              className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white px-5 py-2.5 rounded-lg transition-all transform hover:scale-105 shadow-md"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy All
                </>
              )}
            </button>
          </div>
        </div>

        {/* 1. Refined Problem Statement */}
        <section className="space-y-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center flex-shrink-0">
              <Target className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
            </div>
            <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
              Refined Problem Statement
            </h3>
          </div>
          <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
            {data.problemStatement}
          </p>


        </section>

        <hr className="border-slate-200 dark:border-slate-700" />

        {/* 2. Target Users */}
        <section className="space-y-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-100 dark:bg-emerald-900/30 flex items-center justify-center flex-shrink-0">
              <Users className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
            </div>
            <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
              Target Users
            </h3>
          </div>
          <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
            {data.targetUsers}
          </p>

          {/* User Pain Points */}
          <div className="mt-4">
            <div className="flex items-center gap-2 mb-3">
              <AlertTriangle className="w-4 h-4 text-rose-500" />
              <h4 className="text-sm font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wide">
                Key Pain Points
              </h4>
            </div>
            <ul className="space-y-2.5">
              {data.userPainPoints.map((point, index) => (
                <li key={index} className="flex items-start gap-3 text-slate-600 dark:text-slate-400">
                  <span className="text-rose-500 font-bold mt-1">•</span>
                  <span>{point}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        <hr className="border-slate-200 dark:border-slate-700" />

        {/* 3. Proposed Solution Direction */}
        <section className="space-y-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center flex-shrink-0">
              <Compass className="w-5 h-5 text-amber-600 dark:text-amber-400" />
            </div>
            <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
              Proposed Solution Direction
            </h3>
          </div>
          <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
            {data.solutionDirection}
          </p>

          {/* Key Features */}
          <div className="mt-4">
            <div className="flex items-center gap-2 mb-3">
              <ListChecks className="w-4 h-4 text-amber-600 dark:text-amber-400" />
              <h4 className="text-sm font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wide">
                Key Features
              </h4>
            </div>
            <ul className="space-y-2.5">
              {data.keyFeatures.map((feature, index) => (
                <li key={index} className="flex items-start gap-3 text-slate-600 dark:text-slate-400">
                  <span className="text-amber-600 dark:text-amber-400 font-bold mt-1">✓</span>
                  <span>{feature}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        <hr className="border-slate-200 dark:border-slate-700" />

        {/* 4. Assumptions & Risks */}
        <section className="space-y-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-rose-100 dark:bg-rose-900/30 flex items-center justify-center flex-shrink-0">
              <AlertTriangle className="w-5 h-5 text-rose-600 dark:text-rose-400" />
            </div>
            <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
              Assumptions & Risks
            </h3>
          </div>
          <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
            {data.assumptionsRisks}
          </p>
        </section>

        <hr className="border-slate-200 dark:border-slate-700" />

        {/* 5. Success Metrics */}
        <section className="space-y-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center flex-shrink-0">
              <TrendingUp className="w-5 h-5 text-blue-600 dark:text-blue-400" />
            </div>
            <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
              Success Metrics
            </h3>
          </div>
          <ul className="space-y-2.5">
            {data.successMetrics.map((metric, index) => (
              <li key={index} className="flex items-start gap-3 text-slate-600 dark:text-slate-400">
                <span className="text-blue-600 dark:text-blue-400 font-bold mt-1">📊</span>
                <span>{metric}</span>
              </li>
            ))}
          </ul>
        </section>

        <hr className="border-slate-200 dark:border-slate-700" />

        {/* 6. Technical Considerations */}
        <section className="space-y-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center flex-shrink-0">
              <Code className="w-5 h-5 text-purple-600 dark:text-purple-400" />
            </div>
            <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
              Technical Considerations
            </h3>
          </div>
          <div className="bg-purple-50 dark:bg-purple-950/20 p-4 rounded-lg border border-purple-200 dark:border-purple-800">
            <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
              {data.technicalConsiderations}
            </p>
          </div>
        </section>

        <hr className="border-slate-200 dark:border-slate-700" />

        {/* 7. Next Steps */}
        <section className="space-y-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-green-100 dark:bg-green-900/30 flex items-center justify-center flex-shrink-0">
              <ListChecks className="w-5 h-5 text-green-600 dark:text-green-400" />
            </div>
            <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
              Recommended Next Steps
            </h3>
          </div>
          <ol className="space-y-3">
            {data.nextSteps.map((step, index) => (
              <li key={index} className="flex items-start gap-3 text-slate-600 dark:text-slate-400">
                <span className="flex-shrink-0 w-6 h-6 rounded-full bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 flex items-center justify-center text-sm font-bold">
                  {index + 1}
                </span>
                <span className="pt-0.5">{step}</span>
              </li>
            ))}
          </ol>
        </section>
      </div>

      {/* Export Options - Bottom */}
      <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-lg p-6">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <h3 className="text-lg font-semibold text-slate-900 dark:text-white flex items-center gap-2">
            <Download className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
            Export Clarification
          </h3>
          <div className="flex gap-3">
            <button
              onClick={exportAsText}
              className="flex items-center gap-2 bg-white dark:bg-slate-800 border-2 border-indigo-200 dark:border-indigo-800 hover:border-indigo-300 dark:hover:border-indigo-700 text-indigo-700 dark:text-indigo-300 px-5 py-2.5 rounded-xl transition-all transform hover:scale-105 font-medium"
            >
              <FileText className="w-4 h-4" />
              Export as TXT
            </button>
            <button
              onClick={exportAsMarkdown}
              className="flex items-center gap-2 bg-purple-600 hover:bg-purple-700 text-white px-5 py-2.5 rounded-xl transition-all transform hover:scale-105 shadow-md font-medium"
            >
              <FileCode className="w-4 h-4" />
              Export as MD
            </button>
          </div>
        </div>
      </div>

      {/* PRD Generation Prompt - Bottom */}
      {showPRDPrompt && (
        <div className="bg-gradient-to-r from-indigo-50 to-purple-50 dark:from-indigo-950/30 dark:to-purple-950/30 border border-indigo-200 dark:border-indigo-800 rounded-2xl p-6 shadow-lg">
          <div className="flex items-start justify-between gap-4">
            <div className="flex-1">
              <div className="flex items-center gap-2 mb-2">
                <FileText className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
                <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
                  Want a Full Product Requirements Document?
                </h3>
              </div>
              <p className="text-slate-700 dark:text-slate-300 mb-4">
                We can generate a comprehensive PRD with detailed specifications, user stories, technical architecture, and implementation timeline based on this clarification.
              </p>
              <div className="flex gap-3">
                <button
                  onClick={() => {
                    setShowPRDPrompt(false);
                    onGeneratePRD?.();
                  }}
                  className="bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-2 rounded-lg transition-colors font-medium"
                >
                  Yes, Generate PRD
                </button>
                <button
                  onClick={() => setShowPRDPrompt(false)}
                  className="bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 px-6 py-2 rounded-lg border border-slate-300 dark:border-slate-600 transition-colors"
                >
                  Not Now
                </button>
              </div>
            </div>
            <button
              onClick={() => setShowPRDPrompt(false)}
              className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-300"
            >
              ✕
            </button>
          </div>
        </div>
      )}
    </div>
  );
}